-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 14:04:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetWeb` DEFAULT CHARACTER SET utf8 ;
USE `projetWeb` ;

-- -----------------------------------------------------
-- Table `projetWeb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_def` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`),
  UNIQUE INDEX `status_id_UNIQUE` (`status_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_firstName` VARCHAR(45) NOT NULL,
  `user_lastName` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_address` VARCHAR(45) NULL,
  `user_city` VARCHAR(45) NULL,
  `user_zipCode` VARCHAR(45) NULL,
  `user_status_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_status_id`),
  UNIQUE INDEX `iduser_UNIQUE` (`user_id` ASC) ,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) ,
  INDEX `fk_user_status1_idx` (`user_status_id` ASC) ,
  CONSTRAINT `fk_user_status1`
    FOREIGN KEY (`user_status_id`)
    REFERENCES `projetWeb`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`locations` (
  `location_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_link` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`image_id`),
  UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`conditions` (
  `condition_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `condition_def` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`condition_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`rareness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`rareness` (
  `rareness_id` INT NOT NULL AUTO_INCREMENT,
  `rareness_def` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rareness_id`),
  UNIQUE INDEX `rareness_id_UNIQUE` (`rareness_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`auctions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`auctions` (
  `auction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `auction_name` VARCHAR(155) NOT NULL,
  `auction_description` LONGTEXT NOT NULL,
  `auction_startDate` DATETIME NOT NULL,
  `auction_finishDate` DATETIME NOT NULL,
  `auction_lordChoice` TINYINT NULL,
  `auction_price` DECIMAL NULL,
  `auction_user_id` INT NOT NULL,
  PRIMARY KEY (`auction_id`, `auction_user_id`),
  INDEX `fk_auction_user1_idx` (`auction_user_id` ASC) ,
  CONSTRAINT `fk_auction_user1`
    FOREIGN KEY (`auction_user_id`)
    REFERENCES `projetWeb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`stamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`stamps` (
  `stamp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stamp_name` VARCHAR(155) NOT NULL,
  `stamp_price` DECIMAL NOT NULL,
  `stamp_description` LONGTEXT NULL,
  `stamp_date` YEAR NULL,
  `stamp_certified` TINYINT NULL,
  `stamp_format` VARCHAR(45) NULL,
  `stamp_color` VARCHAR(45) NULL,
  `stamp_location_id` INT UNSIGNED NULL,
  `stamp_image_id` INT NULL,
  `stamp_condition_id` INT UNSIGNED NULL,
  `stamp_rareness_id` INT NULL,
  `stamp_auction_id` INT UNSIGNED NULL,
  PRIMARY KEY (`stamp_id`, `stamp_location_id`, `stamp_image_id`, `stamp_condition_id`, `stamp_rareness_id`, `stamp_auction_id`),
  INDEX `fk_stamps_locations1_idx` (`stamp_location_id` ASC) ,
  INDEX `fk_stamps_images1_idx` (`stamp_image_id` ASC) ,
  INDEX `fk_stamps_conditions1_idx` (`stamp_condition_id` ASC) ,
  INDEX `fk_stamps_rareness1_idx` (`stamp_rareness_id` ASC) ,
  INDEX `fk_stamps_auctions1_idx` (`stamp_auction_id` ASC) ,
  CONSTRAINT `fk_stamps_locations1`
    FOREIGN KEY (`stamp_location_id`)
    REFERENCES `projetWeb`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stamps_images1`
    FOREIGN KEY (`stamp_image_id`)
    REFERENCES `projetWeb`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stamps_conditions1`
    FOREIGN KEY (`stamp_condition_id`)
    REFERENCES `projetWeb`.`conditions` (`condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stamps_rareness1`
    FOREIGN KEY (`stamp_rareness_id`)
    REFERENCES `projetWeb`.`rareness` (`rareness_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stamps_auctions1`
    FOREIGN KEY (`stamp_auction_id`)
    REFERENCES `projetWeb`.`auctions` (`auction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`category_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`category_news` (
  `category_news_id` INT NOT NULL AUTO_INCREMENT,
  `category_news_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_news_id`),
  UNIQUE INDEX `category_news_id_UNIQUE` (`category_news_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`news` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `news_title` VARCHAR(100) NOT NULL,
  `news_content` VARCHAR(1000) NOT NULL,
  `news_author` VARCHAR(45) NOT NULL,
  `news_date` DATETIME NULL,
  `news_category_id` INT NOT NULL,
  PRIMARY KEY (`news_id`, `news_category_id`),
  UNIQUE INDEX `news_id_UNIQUE` (`news_id` ASC) ,
  INDEX `fk_news_category_news_idx` (`news_category_id` ASC) ,
  CONSTRAINT `fk_news_category_news`
    FOREIGN KEY (`news_category_id`)
    REFERENCES `projetWeb`.`category_news` (`category_news_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`bids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`bids` (
  `bid_id` INT NOT NULL AUTO_INCREMENT,
  `bid_amount` DECIMAL NOT NULL,
  `bid_user_id` INT NOT NULL,
  `bid_auction_id` INT NOT NULL,
  PRIMARY KEY (`bid_id`, `bid_auction_id`, `bid_user_id`),
  UNIQUE INDEX `bet_id_UNIQUE` (`bid_id` ASC) ,
  INDEX `fk_bet_user1_idx` (`bid_user_id` ASC) ,
  INDEX `fk_bet_auction1_idx` (`bid_auction_id` ASC) ,
  CONSTRAINT `fk_bet_user1`
    FOREIGN KEY (`bid_user_id`)
    REFERENCES `projetWeb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bet_auction1`
    FOREIGN KEY (`bid_auction_id`)
    REFERENCES `projetWeb`.`auctions` (`auction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`liked_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`liked_news` (
  `likedNews_user_id` INT NOT NULL,
  `likedNews_news_id` INT NOT NULL,
  PRIMARY KEY (`likedNews_user_id`, `likedNews_news_id`),
  INDEX `fk_liked_news_news1_idx` (`likedNews_news_id` ASC) ,
  CONSTRAINT `fk_liked_news_user1`
    FOREIGN KEY (`likedNews_user_id`)
    REFERENCES `projetWeb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liked_news_news1`
    FOREIGN KEY (`likedNews_news_id`)
    REFERENCES `projetWeb`.`news` (`news_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetWeb`.`liked_auctions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetWeb`.`liked_auctions` (
  `likedAuction_user_id` INT NOT NULL,
  `likedAuction_auction_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`likedAuction_user_id`, `likedAuction_auction_id`),
  INDEX `fk_liked_auction_auction1_idx` (`likedAuction_auction_id` ASC) ,
  CONSTRAINT `fk_liked_auction_user1`
    FOREIGN KEY (`likedAuction_user_id`)
    REFERENCES `projetWeb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liked_auction_auction1`
    FOREIGN KEY (`likedAuction_auction_id`)
    REFERENCES `projetWeb`.`auctions` (`auction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
